import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    background: #313e50;
    in property <string> results: "";
    callback divide-income(string);

    GridLayout {
        spacing: 5px;
        padding: 50px;
        Row {

            Text {
                    text: "Enter Total Income";
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    font-size: 24px;
                    font-weight: 900;
                }
        }
        Row {
            income := LineEdit {
                font-size: 14px;
                horizontal-alignment: center;
                placeholder-text: "Type here your number";
                height: 35px;
            }

        }
        Row {
            Button {
                text: "Calculate";
                primary: true;
                height: 35px;
                clicked => {
                    divide-income(income.text)
                }
            }
        }
        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
